In [ ]:
import IPython.display as ip_display
import sys
sys.modules["IPython.core.display"].display = ip_display.display

In [36]:
import numpy as np
import pandas as pd
from scipy import stats
from ydata_profiling import ProfileReport
import prince

In [20]:
ahs = pd.read_csv('ahs2023_cleaned.csv')

In [12]:
ahs.head(3).T

,0,1,2
DIVISION,New England,West South Central,West South Central
TENURE,NaN,Rented,Owned or being bought by someone in your house...
YRBUILT,1980,1970,1970
UNITSIZE,"2,500 to 2,999 square feet",NaN,"2,000 to 2,499 square feet"
HSHLDTYPE,NaN,Married-couple family household,Married-couple family household
HHRACE,NaN,White only,White only
HHSEX,NaN,Male,Male
HINCP,NaN,48000.0,292500.0
TOTHCAMT,NaN,1093.0,810.0
MARKETVAL,NaN,NaN,245790.0
MAINTAMT,NaN,NaN,201.0
FUSEBLOW,NaN,No fuses / breakers blown in the last 3 months,No fuses / breakers blown in the last 3 months
SEWBREAK,NaN,No breakdowns in the last 3 months,No breakdowns in the last 3 months
ROACH,NaN,Seen a few times in the last 12 months,No signs in the last 12 months
RODENT,NaN,No signs in the last 12 months,No signs in the last 12 months
NOWIRE,Concealed,Concealed,Concealed
PLUGS,Not broken,Not broken,Not broken
COLD,NaN,Broken,Broken
NOTOIL,NaN,Broken,Broken
NOWAT,NaN,Broken,Broken
FLOORHOLE,Broken,Broken,Broken
FNDCRUMB,Broken,Broken,Broken
PAINTPEEL,Broken,Broken,Broken
ROOFHOLE,Broken,Broken,Broken
ROOFSAG,Broken,Broken,Broken
ROOFSHIN,Broken,Broken,Broken
WALLCRACK,Broken,Broken,Broken
WALLSIDE,Broken,Broken,Broken
WALLSLOPE,Broken,Broken,Broken
WINBOARD,Broken,Broken,Broken
WINBROKE,Broken,Not broken,Broken
LEAKI,NaN,Broken,Broken
MOLDBATH,NaN,Broken,Broken

In [ ]:
# ahs[ahs.select_dtypes(include='object').columns] = ahs.select_dtypes(include='object').apply(lambda col: col.astype('category'))

In [17]:
profile = ProfileReport(ahs,
                        title = "2023 American Housing Survey",
                        html = {"style": {"full_width": True}},
                        minimal = False)
profile.to_notebook_iframe()

Summarize dataset: 100%|██████████| 38/38 [00:04<00:00,  7.97it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:13<00:00, 13.81s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]

In [21]:
ahs['TENURE'].value_counts()

TENURE
Owned or being bought by someone in your household    28192
Rented                                                19735
Occupied without payment of rent                        600
Name: count, dtype: int64

In [22]:
ahs.groupby('TENURE').agg({'HINCP': ['count', 'mean']})

                                                    HINCP
                                                    count           mean
TENURE
Occupied without payment of rent                      600   54319.523333
Owned or being bought by someone in your household  28192  134696.380746
Rented                                              19735   60886.215455

In [23]:
stats.f_oneway(ahs.query("TENURE == 'Owned or being bought by someone in your household'")['HINCP'],
               ahs.query("TENURE == 'Rented'")['HINCP'],
               ahs.query("TENURE == 'Occupied without payment of rent'")['HINCP'])

F_onewayResult(statistic=1557.3251799219104, pvalue=0.0)

In [31]:
ahs_corr = ahs[['MARKETVAL', 'YRBUILT']].dropna()
ahs_corr.corr()

           MARKETVAL   YRBUILT
MARKETVAL   1.000000  0.035188
YRBUILT     0.035188  1.000000

In [32]:
stats.pearsonr(ahs_corr['MARKETVAL'], ahs_corr['YRBUILT'])

PearsonRResult(statistic=0.03518752110020667, pvalue=2.62887855509185e-10)

In [34]:
brokenness = ahs[['FUSEBLOW',
       'SEWBREAK', 'ROACH', 'RODENT', 'NOWIRE', 'PLUGS', 'COLD', 'NOTOIL',
       'NOWAT', 'FLOORHOLE', 'FNDCRUMB', 'PAINTPEEL', 'ROOFHOLE', 'ROOFSAG',
       'ROOFSHIN', 'WALLCRACK', 'WALLSIDE', 'WALLSLOPE', 'WINBOARD',
       'WINBROKE', 'LEAKI', 'MOLDBATH']].dropna()
brokenness

,FUSEBLOW,SEWBREAK,ROACH,RODENT,NOWIRE,PLUGS,COLD,NOTOIL,NOWAT,FLOORHOLE,...,ROOFHOLE,ROOFSAG,ROOFSHIN,WALLCRACK,WALLSIDE,WALLSLOPE,WINBOARD,WINBROKE,LEAKI,MOLDBATH
1,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,Seen a few times in the last 12 months,No signs in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Not broken,Broken,Broken
2,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,No signs in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken
3,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,Seen a few times in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Not broken,Broken
6,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,No signs in the last 12 months,Exposed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken
7,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,No signs in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55659,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,No signs in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken
55660,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,No signs in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken
55661,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,No signs in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken
55662,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,No signs in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken
55663,No fuses / breakers blown in the last 3 months,No breakdowns in the last 3 months,No signs in the last 12 months,Seen a few times in the last 12 months,Concealed,Not broken,Broken,Broken,Broken,Broken,...,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken,Broken

In [37]:
MCA = prince.MCA(n_components=2)
MCA = MCA.fit(brokenness)

In [41]:
MCA.column_coordinates(brokenness).sort_values(0)

                                                           0         1
WALLCRACK_Broken                                   -0.110855 -0.002844
RODENT_No signs in the last 12 months              -0.109565 -0.023199
COLD_Broken                                        -0.093872 -0.049547
LEAKI_Broken                                       -0.088288 -0.085813
FNDCRUMB_Broken                                    -0.086900  0.025721
ROACH_No signs in the last 12 months               -0.084313 -0.026520
FUSEBLOW_No fuses / breakers blown in the last ... -0.079576 -0.053792
WINBROKE_Broken                                    -0.079181  0.020570
ROOFSHIN_Broken                                    -0.076268  0.056533
WALLSIDE_Broken                                    -0.065975  0.029008
ROOFSAG_Broken                                     -0.056095  0.041725
PAINTPEEL_Broken                                   -0.056069 -0.002212
ROOFHOLE_Broken                                    -0.054311  0.034804
COLD_Not applicable                                -0.045979  0.611351
WALLSLOPE_Broken                                   -0.040679  0.023998
FLOORHOLE_Broken                                   -0.038398 -0.002356
WINBOARD_Broken                                    -0.035079  0.016211
MOLDBATH_Broken                                    -0.032659 -0.017343
NOTOIL_Broken                                      -0.030577 -0.057993
NOWAT_Broken                                       -0.030074 -0.047653
NOWIRE_Concealed                                   -0.026012 -0.017294
PLUGS_Not broken                                   -0.025373 -0.014958
SEWBREAK_No breakdowns in the last 3 months        -0.024024 -0.052066
ROACH_Seen a few times in the last 12 months        0.438146  0.169522
FUSEBLOW_1 fuse / breaker blown in the last 3 m...  0.541685  0.402403
RODENT_Seen a few times in the last 12 months       0.563504  0.106959
SEWBREAK_Sewage system broke down in the last 3...  0.898760  3.419389
FUSEBLOW_2 fuses / breakers blown in the last 3...  0.944381  0.727002
NOWIRE_Exposed                                      0.990659  0.658626
ROACH_Seen monthly in the last 12 months            1.026853 -0.391607
LEAKI_Not broken                                    1.123731  1.092226
COLD_Not broken                                     1.160767  0.426490
NOWAT_Not broken                                    1.252809  1.985092
RODENT_Seen monthly in the last 12 months           1.372759 -0.173954
FUSEBLOW_3 fuses / breakers blown in the last 3...  1.409262  0.567807
ROACH_Seen weekly in the last 12 months             1.548532  0.535841
PLUGS_Broken                                        1.684140  0.992863
FNDCRUMB_Not broken                                 1.745910 -0.516769
SEWBREAK_One breakdown in the last 3 months for...  1.785559  4.385783
RODENT_Seen weekly in the last 12 months            1.857990  0.557423
WINBROKE_Not broken                                 2.193629 -0.569875
FUSEBLOW_4 or more fuses / breakers blown in th...  2.200655  1.495452
WALLCRACK_Not broken                                2.256650  0.057893
ROOFSHIN_Not broken                                 2.437854 -1.807015
SEWBREAK_Two breakdowns in the last 3 months fo...  2.482986  4.770524
NOTOIL_Not broken                                   2.567726  4.870045
ROACH_Seen daily in the last 12 months              2.725378  1.524013
WALLSIDE_Not broken                                 2.759532 -1.213308
RODENT_Seen daily in the last 12 months             3.222933  1.327495
PAINTPEEL_Not broken                                3.357471  0.132464
MOLDBATH_Not broken                                 3.371243  1.790309
ROOFSAG_Not broken                                  3.431552 -2.552469
WINBOARD_Not broken                                 3.506449 -1.620442
FLOORHOLE_Not broken                                3.664109  0.224788
WALLSLOPE_Not broken                                3.965733 -2.339535
ROOFHOLE_Not broken                                 4.042052 -2.590246
SEWBREAK_Four or more breakdowns in last three ...  4.941879  7.927880
SEWBREAK_Three breakdowns in the last 3 months ...  5.562686  4.759241

In [42]:
MCA.row_coordinates(brokenness).sort_values(0)

              0         1
43817 -0.165798 -0.037809
22812 -0.165798 -0.037809
41536 -0.165798 -0.037809
22809 -0.165798 -0.037809
41537 -0.165798 -0.037809
...         ...       ...
5618   4.536668  0.902719
39845  4.744460  0.061044
10968  4.931044  0.167045
27304  5.367414  0.748755
49510  6.331778  1.281431

[32206 rows x 2 columns]