In [5]:
import numpy as np
import pandas as pd
import requests
import json
import dotenv
import os

A "dot E N V" file, named .env, is a plain text file for storing passwords/keys/secrets.

Because it begins with a . for a filename, it is understood by your computer to be a hidden file. That's extra security.

When using GitHub, always use a .gitignore file. .env will always be one of the ignored files. DO NOT allow your .env file to be uploaded to GitHub.

To load secret keys from the .env file:

In [9]:
dotenv.load_dotenv()
newskey = os.getenv('newskey')

In [7]:
url = 'https://newsapi.org/v2/everything'
params = {'apiKey':newskey,
          'q':'Claudia Sheinbaum'}
r = requests.get(url, params=params)
r

In [8]:
myjson = r.json()
news_df = pd.json_normalize(myjson, record_path=['articles'])
news_df

,author,title,description,url,urlToImage,publishedAt,content,source.id,source.name
0,Ayelet Sheffey,Mexico's president says Trump's 25% tariffs wi...,Mexican President Claudia Sheinbaum said that ...,https://www.businessinsider.com/trump-tariff-m...,https://i.insider.com/67a0e411eb4be2fff9a341d9...,2025-02-03T15:51:10Z,President Donald Trump.Roberto Schmidt / AFP v...,business-insider,Business Insider
1,Brent D. Griffiths,Canada and Trump reach a border deal that dela...,"Earlier in the day, Donald Trump said he had r...",https://www.businessinsider.com/trudeau-trump-...,https://i.insider.com/67a0f794eb4be2fff9a34686...,2025-02-03T21:55:25Z,Canadian Prime Minister Justin Trudeau on Mond...,business-insider,Business Insider
2,None,Who won and lost as Trump's trade war is delay...,"BBC reporters in the US, Canada and Mexico ass...",https://www.bbc.com/news/articles/c805jjk2klko,https://ichef.bbci.co.uk/news/1024/branded_new...,2025-02-04T02:35:34Z,Watch: 'I'm getting angry and anti-American' -...,None,BBC News
3,Matthew Gault,Canadian Politicians ‘Rip Up’ Starlink Contrac...,"There's an election going on in Canada, and it...",https://gizmodo.com/canadian-politicians-rip-u...,https://gizmodo.com/app/uploads/2025/02/Canada...,2025-02-03T17:35:15Z,Ontario Premier Doug Ford said hes ripping up ...,None,Gizmodo.com
4,None,Google Maps will rename Gulf of Mexico to Gulf...,"It is the firm's ""longstanding practice"" to ob...",https://www.bbc.com/news/articles/c8634nwxd46o,https://ichef.bbci.co.uk/news/1024/branded_new...,2025-01-28T12:21:24Z,Google will change the name of the Gulf of Mex...,None,BBC News
...,...,...,...,...,...,...,...,...,...
92,Sacha Carion,Le Mexique se prépare au retour massif de ses ...,Le jour de la seconde investiture de Donald Tr...,https://www.courrierinternational.com/article/...,https://focus.courrierinternational.com/2025/0...,2025-01-21T15:01:20Z,"À peine investi à la Maison-Blanche, le présid...",None,Courrier International
93,ZEIT ONLINE: News -,Einigung kurz vor Fristablauf: Nordamerikanisc...,Hier finden Sie Informationen zu dem Thema „Ei...,https://www.zeit.de/news/2025-02/04/nordamerik...,https://img.zeit.de/news/2025-02/04/nordamerik...,2025-02-04T01:29:08Z,Ein nordamerikanischer Handelskrieg mit ungewi...,die-zeit,Die Zeit
94,hvg@hvg.hu,Elhalasztják a Mexikót sújtó amerikai vámok be...,"Mexikó elnöke, Claudia Sheinbaum azt közölte, ...",https://hvg.hu/gazdasag/20250203_Egy-honapra-f...,https://img.hvg.hu/Img/7fcefbf8-ac48-4ee6-aef5...,2025-02-03T16:08:02Z,"Donald Trump megersítette, hogy a mexikói áruk...",None,Hvg.hu
95,Fred Kaplan,The Real Cost of Trump’s Tariff Brinkmanship,Was this a case study of Trump’s mastery in “t...,https://slate.com/news-and-politics/2025/02/tr...,https://compote.slate.com/images/6d5a50b2-7e14...,2025-02-04T19:58:47Z,Sign up for the Slatest to get the most insigh...,None,Slate Magazine
96,Hafiz Rashid,Trump Promises to Rename Gulf of Mexico in Dar...,Donald Trump will rename the Gulf of Mexico an...,https://newrepublic.com/post/190448/trump-rena...,https://images.newrepublic.com/272cf10a3001700...,2025-01-20T18:44:39Z,Trump first announced his plans to rename the ...,None,The New Republic

## Congress API

In [ ]:
congresskey = os.getenv('congresskey')

### User agent strings

A user agent string is a string that informs the API what kind of system you are using to access the API. It's considered good etiquette to include one, and it is sometimes required by the API.

https://httpbin.org/user-agent

In [1]:
url = 'https://httpbin.org/user-agent'
r = requests.get(url)
myjson = r.json()
useragent = myjson['user-agent']

NameError: name 'requests' is not defined

In [12]:
headers = {'User-Agent': useragent,
           'From': 'robertclayh@icloud.com'}

Four things to look for in API documentation:

1. The root
2. The endpoint for the data source you need
3. The parameters
4. Headers, or other instructions for supplying your API key

In [19]:
root = 'https://api.congress.gov/v3' # the beginning of all URLs attached to this API
endpoint = '/member' # the endpoint we want to access
params = {'format':'json',
          'limit':250,
          'offset':0,
          'currentMember':'true',
          'api_key':congresskey} # the parameters we want to pass to the API
r = requests.get(root+endpoint, headers=headers, params=params) # the full URL we want to access
r

In [20]:
myjson = json.loads(r.text)

In [21]:
congress_df = pd.json_normalize(myjson, record_path=['members'])
congress_df

,bioguideId,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item,district
0,K000394,"Kim, Andy",Democratic,New Jersey,2025-01-30T15:59:23Z,https://api.congress.gov/v3/member/K000394?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/k000394_20...,"[{'chamber': 'House of Representatives', 'endY...",NaN
1,B001305,"Budd, Ted",Republican,North Carolina,2025-01-30T15:59:01Z,https://api.congress.gov/v3/member/B001305?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/b001305_20...,"[{'chamber': 'House of Representatives', 'endY...",NaN
2,M001243,"McCormick, David",Republican,Pennsylvania,2025-01-30T15:58:34Z,https://api.congress.gov/v3/member/M001243?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/677d85e0fd...,"[{'chamber': 'Senate', 'startYear': 2025}]",NaN
3,S001232,"Sheehy, Tim",Republican,Montana,2025-01-30T15:57:54Z,https://api.congress.gov/v3/member/S001232?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/677d8231fd...,"[{'chamber': 'Senate', 'startYear': 2025}]",NaN
4,S001230,"Subramanyam, Suhas",Democratic,Virginia,2025-01-27T17:28:58Z,https://api.congress.gov/v3/member/S001230?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6797be8bc7...,"[{'chamber': 'House of Representatives', 'star...",10.0
...,...,...,...,...,...,...,...,...,...,...
245,O000174,"Ossoff, Jon",Democratic,Georgia,2024-11-04T13:42:26Z,https://api.congress.gov/v3/member/O000174?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/o000174_20...,"[{'chamber': 'Senate', 'startYear': 2021}]",NaN
246,M001169,"Murphy, Christopher",Democratic,Connecticut,2024-11-04T13:42:26Z,https://api.congress.gov/v3/member/M001169?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/m001169_20...,"[{'chamber': 'House of Representatives', 'endY...",NaN
247,M001111,"Murray, Patty",Democratic,Washington,2024-11-04T13:42:26Z,https://api.congress.gov/v3/member/M001111?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/m001111_20...,"[{'chamber': 'Senate', 'startYear': 1993}]",NaN
248,M001190,"Mullin, Markwayne",Republican,Oklahoma,2024-11-04T13:42:25Z,https://api.congress.gov/v3/member/M001190?for...,<p>Official U.S. Senate Photo</p>,https://www.congress.gov/img/member/m001190_20...,"[{'chamber': 'House of Representatives', 'endY...",NaN
249,M000934,"Moran, Jerry",Republican,Kansas,2024-11-04T13:42:25Z,https://api.congress.gov/v3/member/M000934?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/m000934_20...,"[{'chamber': 'House of Representatives', 'endY...",NaN

In [49]:
dotenv.load_dotenv()
feckey = os.getenv('feckey')
if feckey is None:
    print("API key not found. Please set the 'feckey' environment variable.")
else:
    print("API key found.")

API key found.

Four things to look for in API documentation:

1. The root
2. The endpoint for the data source you need
3. The parameters
4. Headers, or other instructions for supplying your API key

In [50]:
# Define the root URL and endpoint
root = 'https://api.open.fec.gov'
endpoint = '/v1/candidates/search'

# Define the parameters, including the API key
params = {
    'api_key': feckey,
    'q': 'Trump'
}

# Make the GET request
r = requests.get(root + endpoint, params=params, headers=headers)

# Check the response
print(r)
print(r.json())

<Response [200]>
{'api_version': '1.0', 'pagination': {'count': 6, 'is_count_exact': True, 'page': 1, 'pages': 1, 'per_page': 20}, 'results': [{'active_through': 2022, 'candidate_id': 'S2AK00176', 'candidate_inactive': False, 'candidate_status': 'N', 'cycles': [2022, 2024], 'district': '00', 'district_number': 0, 'election_districts': ['00'], 'election_years': [2022], 'federal_funds_flag': False, 'first_file_date': '2021-08-15', 'has_raised_funds': True, 'inactive_election_years': None, 'incumbent_challenge': 'C', 'incumbent_challenge_full': 'Challenger', 'last_f2_date': '2021-08-15', 'last_file_date': '2021-08-15', 'load_date': '2021-12-08T06:50:51', 'name': 'STEPHENS, JOE TRUMP AKA NOT MURKOWSKI', 'office': 'S', 'office_full': 'Senate', 'party': 'AKI', 'party_full': 'ALASKAN INDEPENDENCE PARTY', 'principal_committees': [{'affiliated_committee_name': 'NONE', 'candidate_ids': ['S2AK00176'], 'committee_id': 'C00787093', 'committee_type': 'S', 'committee_type_full': 'Senate', 'cycles': [2022, 2024], 'designation': 'P', 'designation_full': 'Principal campaign committee', 'filing_frequency': 'T', 'first_f1_date': '2021-08-13', 'first_file_date': '2021-08-13', 'last_f1_date': '2021-08-13', 'last_file_date': '2023-01-12', 'name': 'JOE STEPHENS SENATE CAMPAIGN', 'organization_type': None, 'organization_type_full': None, 'party': 'AKI', 'party_full': 'ALASKAN INDEPENDENCE PARTY', 'state': 'AK', 'treasurer_name': 'STEPHENS, JOE'}], 'state': 'AK'}, {'active_through': 2024, 'candidate_id': 'P80001571', 'candidate_inactive': False, 'candidate_status': 'C', 'cycles': [1988, 2012, 2016, 2018, 2020, 2022, 2024, 2026], 'district': '00', 'district_number': 0, 'election_districts': ['00', '00', '00', '00'], 'election_years': [1988, 2016, 2020, 2024], 'federal_funds_flag': False, 'first_file_date': '2015-06-22', 'has_raised_funds': True, 'inactive_election_years': None, 'incumbent_challenge': 'C', 'incumbent_challenge_full': 'Challenger', 'last_f2_date': '2024-08-20', 'last_file_date': '2024-08-20', 'load_date': '2024-08-20T21:00:26', 'name': 'TRUMP, DONALD J.', 'office': 'P', 'office_full': 'President', 'party': 'REP', 'party_full': 'REPUBLICAN PARTY', 'principal_committees': [{'affiliated_committee_name': 'TRUMP BILIRAKIS VICTORY FUND', 'candidate_ids': ['P80001571'], 'committee_id': 'C00828541', 'committee_type': 'N', 'committee_type_full': 'PAC - Nonqualified', 'cycles': [2022, 2024, 2026], 'designation': 'D', 'designation_full': 'Leadership PAC', 'filing_frequency': 'Q', 'first_f1_date': '2022-11-15', 'first_file_date': '2022-11-15', 'last_f1_date': '2025-01-31', 'last_file_date': '2025-01-31', 'name': 'NEVER SURRENDER, INC.', 'organization_type': None, 'organization_type_full': None, 'party': 'REP', 'party_full': 'REPUBLICAN PARTY', 'state': 'VA', 'treasurer_name': 'CRATE, BRADLEY T.'}, {'affiliated_committee_name': 'TRUMP MAKE AMERICA GREAT AGAIN COMMITTEE', 'candidate_ids': ['P80001571'], 'committee_id': 'C00580100', 'committee_type': 'Q', 'committee_type_full': 'PAC - Qualified', 'cycles': [2016, 2018, 2020, 2022, 2024, 2026], 'designation': 'U', 'designation_full': 'Unauthorized', 'filing_frequency': 'Q', 'first_f1_date': '2015-06-29', 'first_file_date': '2015-06-29', 'last_f1_date': '2025-01-31', 'last_file_date': '2025-01-31', 'name': 'MAKE AMERICA GREAT AGAIN PAC', 'organization_type': None, 'organization_type_full': None, 'party': 'REP', 'party_full': 'REPUBLICAN PARTY', 'state': 'VA', 'treasurer_name': 'CRATE, BRADLEY T. MR.'}], 'state': 'US'}, {'active_through': 2028, 'candidate_id': 'P80007008', 'candidate_inactive': False, 'candidate_status': 'N', 'cycles': [2024, 2026], 'district': '00', 'district_number': 0, 'election_districts': ['00'], 'election_years': [2028], 'federal_funds_flag': False, 'first_file_date': '2024-12-17', 'has_raised_funds': False, 'inactive_election_years': None, 'incumbent_challenge': None, 'incumbent_challenge_full': None, 'last_f2_date': '2024-12-17', 'last_file_date': '2024-12-31', 'load_date': '2024-12-18T21:12:02', 'name': 'TRUMP, DONALD JOHN MR.', 'office': 'P', 'office_full': 'President', 'party': 'REP', 'party_full': 'REPUBLICAN PARTY', 'principal_committees': [], 'state': 'US'}, {'active_through': 2016, 'candidate_id': 'P60018991', 'candidate_inactive': False, 'candidate_status': 'N', 'cycles': [2016], 'district': '00', 'district_number': 0, 'election_districts': ['00'], 'election_years': [2016], 'federal_funds_flag': False, 'first_file_date': '2016-01-08', 'has_raised_funds': False, 'inactive_election_years': None, 'incumbent_challenge': 'O', 'incumbent_challenge_full': 'Open seat', 'last_f2_date': '2016-01-08', 'last_file_date': '2016-01-08', 'load_date': '2016-11-17T06:10:49', 'name': "TRUMP, DON'T VOTE FOR", 'office': 'P', 'office_full': 'President', 'party': 'COM', 'party_full': 'COMMUNIST PARTY', 'principal_committees': [], 'state': 'US'}, {'active_through': 2016, 'candidate_id': 'P60018835', 'candidate_inactive': False, 'candidate_status': 'N', 'cycles': [2016], 'district': '00', 'district_number': 0, 'election_districts': ['00'], 'election_years': [2016], 'federal_funds_flag': False, 'first_file_date': '2016-01-02', 'has_raised_funds': False, 'inactive_election_years': None, 'incumbent_challenge': 'O', 'incumbent_challenge_full': 'Open seat', 'last_f2_date': '2016-01-02', 'last_file_date': '2016-01-02', 'load_date': '2016-11-17T06:10:49', 'name': 'TRUMP, THE MUSLIM DICTATOR', 'office': 'P', 'office_full': 'President', 'party': 'REP', 'party_full': 'REPUBLICAN PARTY', 'principal_committees': [], 'state': 'US'}, {'active_through': 2004, 'candidate_id': 'S4MD00236', 'candidate_inactive': False, 'candidate_status': 'N', 'cycles': [2004], 'district': '00', 'district_number': 0, 'election_districts': ['00'], 'election_years': [2004], 'federal_funds_flag': False, 'first_file_date': '2004-11-17', 'has_raised_funds': False, 'inactive_election_years': None, 'incumbent_challenge': 'C', 'incumbent_challenge_full': 'Challenger', 'last_f2_date': None, 'last_file_date': '2004-11-17', 'load_date': '2004-11-23T00:00:00', 'name': 'TRUMP, THOMAS MATTHEW', 'office': 'S', 'office_full': 'Senate', 'party': 'CON', 'party_full': 'CONSTITUTION PARTY', 'principal_committees': [], 'state': 'MD'}]}

In [1]:
import requests
r = requests.get("https://en.wikipedia.org/wiki/Wikipedia")
r

In [3]:
r = requests.get("https://www.virginia.edu/kazoosymphony")
r